### ISSUE TITLE
Support markdown for forthcoming openmm examples / tutorials

### ISSUE THREAD

**Issue by mpharrigan** [pandegroup/openmm-org#15]
@jchodera and company are working on examples / tutorials to support the openmm paper. Per the openmm call last Friday, we want them on the openmm website. I think @jchodera has them in markdown format.

I'm going to add the jekyll static site generator (used via github pages) so we can support markdown documents. I'll also refactor out the boilderplate html (styling, menus). The current pages will stay as html

@jchodera : do you have drafts of the documents that I can use as placeholders?

**Comment by jchodera** [comment]
Yes! See here:

https://github.com/choderalab/openmm7tutorials

More figures and some updates coming.

**Comment by jchodera** [comment]
This is now implemented thanks to @mpharrigan!
