### ISSUE TITLE
Permit additional users to commit to master

### ISSUE THREAD

**Issue by Lnaden** [pandegroup/openmm-org#17]
Reminder issue per call today to allow at least @jchodera write access to this repo, and possibly me (@lnaden) to make managing the site less burdensome on a few people. Also allows easier example additions.

**Comment by jchodera** [comment]
I'd also like some credentials to access the `openmm.org` S3 bucket in case I have to do some manual cleanup.

I want to get this up before my talk on developing with OpenMM at the Tue 15 Aug at the [E-CAM meeting](https://www.lorentzcenter.nl/lc/web/2017/905/program.php3?wsid=905&venue=Snellius). Can someone give me access to the repo and S3 ASAP?

**Comment by peastman** [comment]
Done.  We should still make changes through pull requests, though, so people can review them first.

> I'd also like some credentials to access the openmm.org S3 bucket

I don't know who manages that.  Maybe ask Theresa?

**Comment by jchodera** [comment]
I think it was originally @rmcgibbo

**Comment by jchodera** [comment]
> Done. 

Thanks!

> We should still make changes through pull requests, though, so people can review them first.

To clarify, I think we should still make changes to `master` through pull requests from `preview`, but that it will be useful to make changes to `preview` that would allow us to review a live version of the page and make changes.

After merging #19, I think we should
* push a copy of `master` to `preview`
* protect the `master` branch from direct commits

**Comment by Lnaden** [comment]
I'm +1 on continuing changes by PR into `preview` and locking `master` from direct commits.

**Comment by jchodera** [comment]
I've been added to the repo (and I think @lnaden too).

**Comment by Lnaden** [comment]
Im a collaborator at the very least, so I should be good
