### ISSUE TITLE
Error while trying to install the openmmforcefields conda package

### ISSUE THREAD

**Issue by kbaitsi** [pandegroup/openmm-org#76]
I have been trying to install the openmmforcefields conda package following the instructions on http://docs.openmm.org/latest/userguide/application/02_running_sims.html#force-fields (conda install -c conda-forge openmmforcefields). However I keep getting the same result shown in the picture below. Any suggestions? I have anaconda installed on Windows 10. 
![Στιγμιότυπο οθόνης 2021-10-07 103643](https://user-images.githubusercontent.com/92086449/136356566-c9cec31c-451f-40f8-8368-0739161a38fe.png)
.

**Comment by raimis** [comment]
@kbaitsi you should this to https://github.com/openmm/openmmforcefields.

**Comment by kbaitsi** [comment]
Thank you for your comment, but that didn't work either. I tried conda install --yes -c conda-forge openmmforcefields
and the instructions here https://open-forcefield-toolkit.readthedocs.io/en/0.8.0/installation.html. I also created a new environment with python 3.6 because python 3.10 still has issues with conda forge but none of these worked...
